-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 16:56:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies2` ;

-- -----------------------------------------------------
-- Schema movies2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies2` DEFAULT CHARACTER SET utf8 ;
USE `movies2` ;

-- -----------------------------------------------------
-- Table `movies2`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies2`.`ratings` ;

CREATE TABLE IF NOT EXISTS `movies2`.`ratings` (
  `tconst` VARCHAR(12) NOT NULL,
  `average_rating` FLOAT NULL,
  `number_of_votes` INT NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies2`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies2`.`title_basics` ;

CREATE TABLE IF NOT EXISTS `movies2`.`title_basics` (
  `tconst` VARCHAR(12) NOT NULL,
  `primary_title` VARCHAR(250) NULL,
  `start_year` INT NULL,
  `runtime` INT NULL,
  `ratings_tconst` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`tconst`, `ratings_tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies2`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies2`.`genres` ;

CREATE TABLE IF NOT EXISTS `movies2`.`genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movies2`.`title_basics_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies2`.`title_basics_has_genres` ;

CREATE TABLE IF NOT EXISTS `movies2`.`title_basics_has_genres` (
  `title_basics_tconst` VARCHAR(12) NOT NULL,
  `genres_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `genres_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
